START TRANSACTION;
DROP DATABASE IF EXISTS todo_list;
CREATE DATABASE IF NOT EXISTS todo_list;
USE todo_list;
CREATE TABLE IF NOT EXISTS task (
    id INT(10) NOT NULL AUTO_INCREMENT,
    title VARCHAR(50) NOT NULL,
    description VARCHAR(150) NOT NULL,
    important BOOLEAN DEFAULT FALSE NOT NULL,
    PRIMARY KEY (id)
);
COMMIT;
